== Developer guide



=== Setting the database

==== Install MySQL +
Download Community Server (5.7.44 version):

Web-page:: https://downloads.mysql.com/archives/community/
Product:: https://downloads.mysql.com/archives/get/p/23/file/mysql-5.7.44-winx64.zip

More info on: +
https://dev.mysql.com/doc/refman/5.7/en/ +

==== Configure local data +

Copy and update `my_config.ini` file in MySQL using the sibling file. +
In *Administrator* CMD, run:

[source,bash]
----
bin\mysqld --defaults-file=my-config.ini --initialize-insecure
----
This command creates a server with 'root' account and no password (~= insecure). +

==== Starting DB

To start the MySQL database if not installed as a service. (or copy and use "start-server.bat" in installation)

[source,bash]
----
bin\mysqld --defaults-file=my-config.ini --console
---- 

To start client: 
[source,bash]
----
bin\mysql -u root --skip-password
----


[NOTE]
====
You can change root password with:
[source,sql]
----
ALTER USER 'root'@'localhost' IDENTIFIED BY 'new-root-password';
---- 
But it is useless for developer.
====

==== Create schema

Use in MySQL client: `/misc/sql/createDatabase.sql`
[source,bash]
----
bin\mysql -u root --skip-password < %git_home%\Activity-Manager\misc\sql\createDatabase.sql
---- 

Create a connection in *_Data Source Explorer_* from +
`/org.activitymgr.ui.web.feature/cfg-db.properties`


==== Stopping DB

The proper way to stop is to call this command.

[source,bash]
----
bin\mysqladmin -u root shutdown
----

Using console "Close" may break a transaction.

=== Configure Db client with Eclipse

.Get Eclipse instance from Oomph

Use `/parent/oomph/org.eclipse.setup` to get all SQL plugins for Eclipse IDE.

.Import a connection

In *_Data Source Explorer_* View (*_Database development_* Perspective), import `/misc/doc/eclipse_dbconnection_localtest.xml`.

.Declare MySQL driver

Importing a connection also declare the driver but JAR file is absolute.

Driver is placed at `/misc/sql/mysql-connector-java-8.0.27.jar`, mirror of:
https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-8.0.27.zip

In _Windows/Preference#Data manager/Connectivity/Driver definition_: +
Correct 'MySQL JDBC Driver' with provided JAR if needed.


=== Initialize database structure

[source,bash]
----
bin\mysql --user=taskmgr --password=taskmgr taskmgr_db < %git_home%\Activity-Manager\misc\sql\createTables.sql
----

or use eclipse connection with `misc/sql/createTables.sql`.